namespace WoadRaiders.Core;

/// <summary>
/// The realms a raider can choose. Serialized as a byte in the join request,
/// so keep the numbering stable.
/// </summary>
public enum DungeonId : byte
{
    Crag = 0, // the open highland realm (generated by tools/GenerateRealm.cs)
}

/// <summary>One shipping realm: identity, flavor, and where its files live.</summary>
public readonly record struct DungeonInfo(
    DungeonId Id,
    string Name,
    string Tagline,
    string MapFile,   // geometry JSON in the maps directory (canonical copy: WoadRaiders.Client/maps),
                      // baked from the realm's .tscn scene
    string ScenePath, // the authored res:// scene the client renders (terrain realms fall back
                      // to rendering from the geometry when a client lacks the scene)
    string MusicKey); // assets/audio/<key>_theme.wav

/// <summary>
/// The realm table. Kept in Core so the server (which maps to host), the
/// client (the selection screen, music), and the tests all agree on it.
/// </summary>
public static class DungeonCatalog
{
    public static readonly DungeonInfo[] All =
    {
        new(DungeonId.Crag, "The Crag",
            "A broken highland — glen and gorge, the windswept moor, and the walled court on the summit.",
            "Crag.json", "res://maps/Crag.tscn", "barrow"),
    };

    public static DungeonInfo Of(DungeonId id) => All[(int)id];

    /// <summary>Coerce an untrusted byte (the wire, a CLI arg) to a known realm.</summary>
    public static DungeonId Sanitize(byte id) => id < All.Length ? (DungeonId)id : All[0].Id;

    /// <summary>The catalog entry rendering this scene, if any (drives per-realm music).</summary>
    public static DungeonInfo? ForScene(string scenePath)
    {
        foreach (var info in All)
            if (info.ScenePath == scenePath)
                return info;
        return null;
    }
}
